[package]
name = "engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
renderer = { workspace = true }
winit = "0.30"

[lints]
workspace = true
