[package]
name = "engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
renderer = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
winit = "0.30"

[lints]
workspace = true
